
import type { Language } from './types';

export const GEMINI_MODEL = 'gemini-2.5-flash';

type TranslationKeys = {
  title: string;
  uploadTitle: string;
  uploadSubtitle: string;
  uploadPlaceholder: string;
  uploadButton: string;
  changeFile: string;
  analyzeButton: string;
  analyzingButton: string;
  patientView: string;
  doctorView: string;
  errorTitle: string;
  errorNoFile: string;
  errorFileRead: string;
  errorAnalysis: string;
  disclaimerTitle: string;
  disclaimerContent: string;
  footer: string;
  patientReport: {
    title: string;
    overallImpression: string;
    keyFindings: string;
    recommendations: string;
  };
  doctorReport: {
    title: string;
    professionalSummary: string;
    detailedResults: string;
    testName: string;
    value: string;
    unit: string;
    referenceRange: string;
    status: string;
    interpretation: string;
  };
};

export const translations: Record<Language, TranslationKeys> = {
  en: {
    title: "MediReport Analyzer AI",
    uploadTitle: "Upload Your Medical Report",
    uploadSubtitle: "Upload an image (PNG, JPG) or a PDF of your lab report for an AI-powered analysis.",
    uploadPlaceholder: "Click to upload or drag and drop",
    uploadButton: "Select file",
    changeFile: "Change file",
    analyzeButton: "Analyze Report",
    analyzingButton: "Analyzing...",
    patientView: "Patient View",
    doctorView: "Doctor View",
    errorTitle: "Error",
    errorNoFile: "Please select a file to analyze.",
    errorFileRead: "Could not read the selected file. Please try again.",
    errorAnalysis: "An error occurred during analysis. The model may be unable to process this report. Please try another file.",
    disclaimerTitle: "Important Disclaimer",
    disclaimerContent: "This analysis is generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.",
    footer: "All rights reserved.",
    patientReport: {
      title: "Simplified Patient Summary",
      overallImpression: "Overall Impression",
      keyFindings: "Key Findings",
      recommendations: "Recommendations",
    },
    doctorReport: {
      title: "Detailed Professional Report",
      professionalSummary: "Professional Summary",
      detailedResults: "Detailed Results",
      testName: "Test Name",
      value: "Value",
      unit: "Unit",
      referenceRange: "Reference Range",
      status: "Status",
      interpretation: "Interpretation",
    },
  },
  ar: {
    title: "محلل التقارير الطبية بالذكاء الاصطناعي",
    uploadTitle: "ارفع تقريرك الطبي",
    uploadSubtitle: "ارفع صورة (PNG, JPG) أو ملف PDF لتقرير المختبر للحصول على تحليل مدعوم بالذكاء الاصطناعي.",
    uploadPlaceholder: "انقر للتحميل أو اسحب وأفلت الملف",
    uploadButton: "اختر ملفًا",
    changeFile: "تغيير الملف",
    analyzeButton: "تحليل التقرير",
    analyzingButton: "جاري التحليل...",
    patientView: "عرض المريض",
    doctorView: "عرض الطبيب",
    errorTitle: "خطأ",
    errorNoFile: "يرجى اختيار ملف لتحليله.",
    errorFileRead: "لا يمكن قراءة الملف المختار. يرجى المحاولة مرة أخرى.",
    errorAnalysis: "حدث خطأ أثناء التحليل. قد لا يتمكن النموذج من معالجة هذا التقرير. يرجى تجربة ملف آخر.",
    disclaimerTitle: "إخلاء مسؤولية هام",
    disclaimerContent: "هذا التحليل تم إنشاؤه بواسطة الذكاء الاصطناعي وهو لأغراض إعلامية فقط. لا يعتبر بديلاً عن الاستشارة الطبية المتخصصة أو التشخيص أو العلاج. استشر دائمًا طبيبك أو مقدم الرعاية الصحية المؤهل بشأن أي أسئلة قد تكون لديك بخصوص حالة طبية.",
    footer: "جميع الحقوق محفوظة.",
    patientReport: {
      title: "ملخص مبسط للمريض",
      overallImpression: "الانطباع العام",
      keyFindings: "النتائج الرئيسية",
      recommendations: "التوصيات",
    },
    doctorReport: {
      title: "تقرير احترافي مفصل",
      professionalSummary: "ملخص احترافي",
      detailedResults: "النتائج التفصيلية",
      testName: "اسم الفحص",
      value: "القيمة",
      unit: "الوحدة",
      referenceRange: "النطاق المرجعي",
      status: "الحالة",
      interpretation: "التفسير",
    },
  },
};
   