export const GEMINI_MODEL = 'gemini-2.5-flash';

export const translations = {
  en: {
    disclaimerTitle: "Disclaimer",
    disclaimerContent: "This tool is for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider.",
    patientView: "Patient View",
    doctorView: "Doctor View",
    patientReport: {
      title: "Your Health Report Summary",
      overallImpression: "Overall Impression",
      keyFindings: "Key Findings",
      recommendations: "Recommendations",
      medicalAdvice: "Medical Advice",
      nutritionalAdvice: "Nutritional Advice",
    },
    doctorReport: {
      title: "Doctor's Clinical Report",
      professionalSummary: "Professional Summary",
      detailedResults: "Detailed Results",
      exportPdf: "Export as PDF",
      exportingPdf: "Exporting...",
      copyToClipboard: "Copy to Clipboard",
      copied: "Copied!",
      testName: "Test Name",
      value: "Value",
      unit: "Unit",
      referenceRange: "Reference Range",
      status: "Status",
      interpretation: "Interpretation",
      possibleCauses: "Possible Causes",
      statusTooltips: {
        High: "Value is above the normal reference range.",
        Low: "Value is below the normal reference range.",
        Normal: "Value is within the standard reference range.",
        Borderline: "Value is at the edge of the normal range and may require monitoring.",
        Critical: "Value is at a critically dangerous level, requiring immediate medical attention.",
      },
    },
    history: {
        title: "Analysis History",
        analyzedOn: "Analyzed on",
        noHistory: "No past analyses found.",
        clear: "Clear History",
    },
    fileUpload: {
        title: "Upload Medical Report",
        description: "Upload an image of your lab report to get a detailed analysis in English and Arabic.",
        selectFile: "Select file",
        orDrag: "or drag and drop",
        fileTypes: "PNG, JPG, WEBP up to 10MB",
        analyzing: "Analyzing...",
        error: "Analysis Failed. Please try again.",
        fileTooLarge: "File is too large. Maximum size is 10MB.",
        invalidFileType: "Invalid file type. Please upload a PNG, JPG, or WEBP image."
    },
    appName: "MediScan AI",
    themeToggle: "Toggle theme",
    fullscreenToggle: "Toggle fullscreen",
    fontSizeToggle: "Change font size",
    fontSizeSmall: "Small",
    fontSizeNormal: "Normal",
    fontSizeLarge: "Large",
    pdfExportModal: {
      titlePatient: "Customize Patient PDF Report",
      titleDoctor: "Customize Doctor PDF Report",
      includeSections: "Include Sections",
      fileName: "Filename",
      generatePdf: "Generate PDF",
      cancel: "Cancel",
    },
  },
  ar: {
    disclaimerTitle: "إخلاء مسؤولية",
    disclaimerContent: "هذه الأداة هي لأغراض إعلامية فقط وليست بديلاً عن الاستشارة الطبية المتخصصة أو التشخيص أو العلاج. استشر دائمًا مقدم رعاية صحية مؤهل.",
    patientView: "عرض المريض",
    doctorView: "عرض الطبيب",
    patientReport: {
      title: "ملخص تقريرك الصحي",
      overallImpression: "الانطباع العام",
      keyFindings: "النتائج الرئيسية",
      recommendations: "التوصيات",
      medicalAdvice: "نصائح طبية",
      nutritionalAdvice: "نصائح غذائية",
    },
    doctorReport: {
      title: "التقرير الطبي للطبيب",
      professionalSummary: "ملخص احترافي",
      detailedResults: "النتائج التفصيلية",
      exportPdf: "تصدير PDF",
      exportingPdf: "جاري التصدير...",
      copyToClipboard: "نسخ إلى الحافظة",
      copied: "تم النسخ!",
      testName: "اسم الاختبار",
      value: "القيمة",
      unit: "الوحدة",
      referenceRange: "النطاق المرجعي",
      status: "الحالة",
      interpretation: "التفسير",
      possibleCauses: "الأسباب المحتملة",
      statusTooltips: {
        High: "القيمة أعلى من النطاق المرجعي الطبيعي.",
        Low: "القيمة أقل من النطاق المرجعي الطبيعي.",
        Normal: "القيمة ضمن النطاق المرجعي القياسي.",
        Borderline: "القيمة على حافة النطاق الطبيعي وقد تتطلب المراقبة.",
        Critical: "القيمة في مستوى حرج وخطير، وتتطلب اهتمامًا طبيًا فوريًا.",
      },
    },
    history: {
        title: "سجل التحليلات",
        analyzedOn: "تم التحليل في",
        noHistory: "لا توجد تحليلات سابقة.",
        clear: "مسح السجل",
    },
    fileUpload: {
        title: "تحميل التقرير الطبي",
        description: "قم بتحميل صورة من تقرير المختبر الخاص بك للحصول على تحليل مفصل باللغة الإنجليزية والعربية.",
        selectFile: "اختر ملفًا",
        orDrag: "أو قم بالسحب والإفلات",
        fileTypes: "PNG, JPG, WEBP بحجم يصل إلى 10 ميجابايت",
        analyzing: "جاري التحليل...",
        error: "فشل التحليل. يرجى المحاولة مرة أخرى.",
        fileTooLarge: "الملف كبير جدًا. الحجم الأقصى 10 ميجابايت.",
        invalidFileType: "نوع ملف غير صالح. يرجى تحميل صورة PNG أو JPG أو WEBP."
    },
    appName: "MediScan AI",
    themeToggle: "تبديل المظهر",
    fullscreenToggle: "تبديل وضع ملء الشاشة",
    fontSizeToggle: "تغيير حجم الخط",
    fontSizeSmall: "صغير",
    fontSizeNormal: "عادي",
    fontSizeLarge: "كبير",
    pdfExportModal: {
      titlePatient: "تخصيص تقرير المريض PDF",
      titleDoctor: "تخصيص تقرير الطبيب PDF",
      includeSections: "تضمين الأقسام",
      fileName: "اسم الملف",
      generatePdf: "إنشاء PDF",
      cancel: "إلغاء",
    },
  },
};