import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { DoctorReport as DoctorReportType, Language, PatientSummary, PdfExportOptions } from '../types';
import { translations } from '../constants';
import { AMIRI_FONT_BASE64 } from '../lib/amiri-font';

const APP_LOGO_BASE64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAAGB0lEQVR4nO2a3W9UVRzH//3OzDud2W67pVu6tLulQGA5YGoCjA+i/gDRGCPiHzQxEQmJj/wARUTFhA/8M8aYmKhEfyAq0RhN0CgYEwOYGCBqgEBaOmxb2i6t7Xa7nTlz7j4+uK1t2+12p3OnT+95Tsn3eT7f8/2ec+75PCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQghx24nneV9N0341y7KO4zhvkcvl3ubB17sA5eXl5wutbDb7QllZ2f9abDZbTgBwOOwXACg4M5vNvllZWXlpaRwejt1PAxqN/lC9urm51d1e7wL/LqVS6V2NjVl8fNzs2BqNh8Phn01NTU1VVVXlKcaep+Xl6uzsLCsrq6mpwWAwQRDk5eXR6XQajcYwDBiGCw4OarVa0+k0m81er9fsdrtcLpfL5WA4fHh42Ov1mqaNjo5ubm7Ozs5ubm5+fn5OTk6Ojo5+fHwcHx/Pz88vLy8fHx9PTk4ODg5er5fP5xcXF8fHx/Pz83Nzc7OzsycnJ8fHx+vr6/Pz85OTk4ODg4mJiYmJiZGRkYmJycnJydnZ2dHR0d7eXltbW11dnZ2dDQ8P//jx49raWjabHRwcHBsbk5KSmpqaycnJ+fn54eHh2dnZWlpaycnJkZGRra2tsbGx+fn5sbGxvb29tbW1NTU1mZmZKSkpqampKSkpqampiYmJgYGBCQkJiYmJtbW1NTU1+fn5wcHBpaWl+fn5kZGRwcHBycnJtbW11dXV1dXVzc3N8fHx8fHxpaWlycnJsbGxgYGB8fHx8fHxpaWl+fn5sbGxXV1dTU1NzczMTE1NzcnJCQ8P5/F4SktLW1tbL168ePfu3dHRUU9PT0tLy9bW1tra2sXFxcbGxvb29sfHxzc3Nzc3N8fHx8fHx8bGxsnJyZGRkYmJycnJSUtLa25ubmlp6ezszMzMbG1tDQ0NpaWld+7c2dvbOz09XVFROTExMTk5GRsbS6lUra2te/bsWVRUJCQktLW1JSYmpqamVlZW3rhxY21tbWlpCW1pKS0tLy8vHx8fj4+PX7x4sbS0ZDIZm5ubGxsba2tru7q6BgYGFhcXt7e3q6ursbExl8s9OTl5fHx8enp6fHx8fHx8enr64ODg7Oz83r17IyMjPT09s7Oza2trm5ubg4ODnZycWltbPz4+fvz4cXl5eXx8/OjoadbW1tLS0tLSkpubm5yc/OjRIyUlJW1t7fLy8kOHDmVlZS9evHjz5s2JiYnZ2VlbW9vLy8vXrx8fHx9TU1MLCwtzc3O73W40Ghsbm7u6usrJydnd3ZVKpTCbzOFwuL+/n81mr66u5vP5AwMDsVh8eHj48fHx9PT09vb2ysrKwsLCwsLC+vo6Pz//1tZWqVS2tbXFYrFYLLa2tubu7t63b9+ZM2eam5tTU1MTEhJaWloqKirKzc0tKChQVFSUmJjY2trKZrNUKm1tbcViMTk5mZ6enpycPH/+fHBwMBgMHj161NXV1d3dPTw8jI6OPj4+vr6+T05Ojo+Pj4+PT05Ojo+PHz9+/Pj4+Pj4+PDw8ODgYHJycnJyYmJiYWFhYSEh4eHhWlpa+fn5XV1de3v72NiYnZ2dl5cXExNjampqZWWloaFhaWmpu7t7eXn5+Pg4Nzd3fHy8tLT04ODg9evXf35+zs/Pz87OzsrKGh0dra+vLygoqKioKCsry8vLy8vLy8nJsbW1DQ0Nzc3Np6enfX19/v7+/fv3R4VCsbCw+G+19g/6bJd7dghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIU5b/gA3qj81r6lY9wAAAABJRU5ErkJggg==';

const pageMargin = 15;
const headerHeight = 30; // Increased space for header
const footerHeight = 20;

// Reusable function to add header and footer to all pages of a document
const addHeaderFooter = (doc: jsPDF, language: Language, title: string) => {
    const pageCount = doc.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const isArabic = language === 'ar';
    
    const setDocFont = (style: 'normal' | 'bold' = 'normal', size: number = 10) => {
        doc.setFont(isArabic ? 'Amiri' : 'Helvetica', style);
        doc.setFontSize(size);
    };

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        // -- HEADER --
        doc.addImage(APP_LOGO_BASE64, 'PNG', pageMargin, 8, 14, 14);
        
        setDocFont('bold', 16);
        doc.setTextColor(40);
        const appName = translations[language].appName;
        doc.text(appName, pageWidth / 2, 15, { align: 'center' });
        
        setDocFont('normal', 10);
        doc.setTextColor(100);
        doc.text(title, pageWidth / 2, 22, { align: 'center' });

        doc.setDrawColor(220); 
        doc.setLineWidth(0.2);
        doc.line(pageMargin, headerHeight - 5, pageWidth - pageMargin, headerHeight - 5);

        // -- FOOTER --
        doc.line(pageMargin, pageHeight - footerHeight, pageWidth - pageMargin, pageHeight - footerHeight);
        
        setDocFont('normal', 8);
        doc.setTextColor(150);
        
        const generatorText = `Generated by ${translations.en.appName}`;
        doc.text(generatorText, pageMargin, pageHeight - 10, { align: 'left' });

        const pageNumText = `Page ${i} of ${pageCount}`;
        doc.text(pageNumText, pageWidth - pageMargin, pageHeight - 10, { align: 'right' });
    }
};

export const generateDoctorReportPDF = async (report: DoctorReportType, language: Language, options: PdfExportOptions) => {
    const doc = new jsPDF();
    const tGlobal = translations[language];
    const t = tGlobal.doctorReport;
    const isArabic = language === 'ar';
    const { sections, fileName } = options;

    // Add Amiri font for Arabic support
    doc.addFileToVFS('Amiri-Regular.ttf', AMIRI_FONT_BASE64);
    doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal');

    const setDocFont = (style: 'normal' | 'bold' = 'normal') => {
        doc.setFont(isArabic ? 'Amiri' : 'Helvetica', style);
    };

    let yPos = headerHeight;
    const pageHeight = doc.internal.pageSize.getHeight();
    const usableWidth = doc.internal.pageSize.getWidth() - pageMargin * 2;
    const rtlAlign: { align: 'right' | 'left' } = { align: isArabic ? 'right' : 'left' };
    const textX = isArabic ? doc.internal.pageSize.getWidth() - pageMargin : pageMargin;
    
    // --- Professional Summary ---
    if (sections.professionalSummary) {
        setDocFont('bold');
        doc.setFontSize(14);
        doc.text(t.professionalSummary, textX, yPos, rtlAlign);
        yPos += 8;

        setDocFont('normal');
        doc.setFontSize(10);
        const summaryText = isArabic ? report.summary_ar : report.summary_en;
        
        const splitSummary = doc.splitTextToSize(summaryText, usableWidth);
        doc.text(splitSummary, textX, yPos, rtlAlign);
        const summaryHeight = splitSummary.length * (doc.getLineHeight() / doc.internal.scaleFactor);
        yPos += summaryHeight + 10;
    }


    // --- Detailed Results Table ---
    if (sections.detailedResults) {
        let tableHeaders = [
            t.testName,
            t.value,
            t.unit,
            t.referenceRange,
            t.status,
            t.interpretation,
            t.possibleCauses
        ];

        let tableBody = report.results.map(item => [
            item.testName,
            item.value,
            item.unit,
            item.referenceRange,
            item.status,
            isArabic ? item.interpretation_ar : item.interpretation_en,
            isArabic ? item.possibleCauses_ar : item.possibleCauses_en
        ]);

        let tableColumnStyles: { [key: number]: { cellWidth: number | 'auto' | 'wrap' } } = {
            0: { cellWidth: 35 }, 
            1: { cellWidth: 15 }, 
            2: { cellWidth: 15 }, 
            3: { cellWidth: 25 }, 
            4: { cellWidth: 20 }, 
            5: { cellWidth: 'auto' },
            6: { cellWidth: 'auto' },
        };
        
        if (isArabic) {
            tableHeaders.reverse();
            tableBody.forEach(row => row.reverse());
            tableColumnStyles = {
                0: { cellWidth: 'auto' },      // Possible Causes
                1: { cellWidth: 'auto' },      // Interpretation
                2: { cellWidth: 20 },          // Status
                3: { cellWidth: 25 },          // Reference Range
                4: { cellWidth: 15 },          // Unit
                5: { cellWidth: 15 },          // Value
                6: { cellWidth: 35 },          // Test Name
            }
        }

        autoTable(doc, {
            head: [tableHeaders],
            body: tableBody,
            startY: yPos,
            margin: { left: pageMargin, right: pageMargin, top: headerHeight },
            styles: {
                font: isArabic ? 'Amiri' : 'Helvetica',
                fontStyle: 'normal',
                halign: isArabic ? 'right' : 'left',
                valign: 'middle', 
                cellPadding: 3,
            },
            headStyles: {
                font: isArabic ? 'Amiri' : 'Helvetica',
                fontStyle: 'bold',
                fillColor: [41, 128, 185],
                textColor: 255,
                halign: 'center',
            },
            alternateRowStyles: {
                fillColor: [245, 245, 245],
            },
            columnStyles: tableColumnStyles,
            didDrawPage: (data) => {
                // Update yPos after table renders a page
                yPos = data.cursor?.y ?? headerHeight;
            }
        });
    }

    if (sections.disclaimer) {
        // Ensure there is enough space for the disclaimer on the current page, or add a new one.
        const lastAutoTableY = (doc as any).lastAutoTable.finalY || yPos;
        if (lastAutoTableY > pageHeight - footerHeight - 30) {
             // autoTable should have already added a page, but if not, we do.
             // We just need to reset yPos if a new page was added.
            if ((doc as any).lastAutoTable.pageCount > (doc as any).lastAutoTable.pageNumber) {
                 yPos = headerHeight;
            } else {
                 yPos = lastAutoTableY + 10;
            }
        } else {
            yPos = lastAutoTableY + 10;
        }

        doc.setLineWidth(0.5);
        doc.line(pageMargin, yPos, doc.internal.pageSize.getWidth() - pageMargin, yPos);
        yPos += 10;
        
        setDocFont('bold');
        doc.setFontSize(10);
        doc.text(tGlobal.disclaimerTitle, textX, yPos, rtlAlign);
        yPos += 6;

        setDocFont('normal');
        doc.setFontSize(8);
        const disclaimerLines = doc.splitTextToSize(tGlobal.disclaimerContent, usableWidth);
        doc.text(disclaimerLines, textX, yPos, rtlAlign);
    }


    addHeaderFooter(doc, language, t.title);
    
    const pdfBlob = doc.output('blob');

    // Use the modern File System Access API if available
    if ('showSaveFilePicker' in window) {
        try {
            const handle = await (window as any).showSaveFilePicker({
                suggestedName: fileName,
                types: [{
                    description: 'PDF Documents',
                    accept: { 'application/pdf': ['.pdf'] },
                }],
            });
            const writable = await handle.createWritable();
            await writable.write(pdfBlob);
            await writable.close();
            return; // Success!
        } catch (err: any) {
            // If the user cancels the dialog, it's not an error, so we can just return.
            if (err.name === 'AbortError') {
                return;
            }
            // Log other errors and fall back to the old method.
            console.error("Could not save PDF with File System Access API, falling back.", err);
        }
    }

    // Fallback for older browsers
    const url = URL.createObjectURL(pdfBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};


export const generatePatientReportPDF = async (summary: PatientSummary, language: Language, options: PdfExportOptions) => {
    const doc = new jsPDF();
    const t = translations[language];
    const patientT = t.patientReport;
    const isArabic = language === 'ar';
    const { sections, fileName } = options;

    // Add Amiri font for Arabic support
    doc.addFileToVFS('Amiri-Regular.ttf', AMIRI_FONT_BASE64);
    doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal');

    const setDocFont = (style: 'normal' | 'bold' = 'normal') => {
        doc.setFont(isArabic ? 'Amiri' : 'Helvetica', style);
    };
    
    const pageHeight = doc.internal.pageSize.getHeight();
    const usableWidth = doc.internal.pageSize.getWidth() - pageMargin * 2;
    let yPos = headerHeight;
    const rtlAlign: { align: 'right' | 'left' } = { align: isArabic ? 'right' : 'left' };
    const textX = isArabic ? doc.internal.pageSize.getWidth() - pageMargin : pageMargin;

    // Helper to render a section with title and content
    const renderSection = (title: string, content: string | string[]) => {
        if (!content || (Array.isArray(content) && content.length === 0)) return;

        // Check if a page break is needed before rendering the section title
        if (yPos > pageHeight - footerHeight - 30) {
            doc.addPage();
            yPos = headerHeight;
        }

        setDocFont('bold');
        doc.setFontSize(14);
        doc.text(title, textX, yPos, rtlAlign);
        yPos += 8;

        setDocFont('normal');
        doc.setFontSize(10);
        
        const checkAndAddPage = (requiredHeight: number) => {
            if (yPos + requiredHeight > pageHeight - footerHeight - 10) {
                doc.addPage();
                yPos = headerHeight;
            }
        };

        if (Array.isArray(content)) {
            content.forEach(item => {
                const itemText = `• ${item}`;
                const textLines = doc.splitTextToSize(itemText, usableWidth);
                checkAndAddPage(textLines.length * 5 + 2);
                doc.text(textLines, textX, yPos, rtlAlign);
                yPos += textLines.length * 5 + 2;
            });
        } else {
            const textLines = doc.splitTextToSize(content, usableWidth);
            checkAndAddPage(textLines.length * 5);
            doc.text(textLines, textX, yPos, rtlAlign);
            yPos += textLines.length * 5;
        }
        yPos += 10;
    };

    if (sections.overallImpression) renderSection(patientT.overallImpression, isArabic ? summary.overallImpression_ar : summary.overallImpression_en);
    if (sections.keyFindings) renderSection(patientT.keyFindings, isArabic ? summary.keyFindings_ar : summary.keyFindings_en);
    if (sections.recommendations) renderSection(patientT.recommendations, isArabic ? summary.recommendations_ar : summary.recommendations_en);
    if (sections.medicalAdvice) renderSection(patientT.medicalAdvice, isArabic ? summary.medicalAdvice_ar : summary.medicalAdvice_en);
    if (sections.nutritionalAdvice) renderSection(patientT.nutritionalAdvice, isArabic ? summary.nutritionalAdvice_ar : summary.nutritionalAdvice_en);
    
    // --- Add Disclaimer ---
    if (sections.disclaimer) {
        if (yPos > pageHeight - footerHeight - 30) {
            doc.addPage();
            yPos = headerHeight;
        }
        yPos += 5;
        doc.setLineWidth(0.5);
        doc.line(pageMargin, yPos, doc.internal.pageSize.getWidth() - pageMargin, yPos);
        yPos += 10;
        
        setDocFont('bold');
        doc.setFontSize(10);
        doc.text(t.disclaimerTitle, textX, yPos, rtlAlign);
        yPos += 6;

        setDocFont('normal');
        doc.setFontSize(8);
        const disclaimerLines = doc.splitTextToSize(t.disclaimerContent, usableWidth);
        doc.text(disclaimerLines, textX, yPos, rtlAlign);
    }

    addHeaderFooter(doc, language, patientT.title);
    
    const pdfBlob = doc.output('blob');

    // Use the modern File System Access API if available
    if ('showSaveFilePicker' in window) {
        try {
            const handle = await (window as any).showSaveFilePicker({
                suggestedName: fileName,
                types: [{
                    description: 'PDF Documents',
                    accept: { 'application/pdf': ['.pdf'] },
                }],
            });
            const writable = await handle.createWritable();
            await writable.write(pdfBlob);
            await writable.close();
            return; // Success!
        } catch (err: any) {
            // If the user cancels the dialog, it's not an error, so we can just return.
            if (err.name === 'AbortError') {
                return;
            }
            // Log other errors and fall back to the old method.
            console.error("Could not save PDF with File System Access API, falling back.", err);
        }
    }
    
    // Fallback for older browsers
    const url = URL.createObjectURL(pdfBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};